name: Cardgamelog
options:
  bundleIdPrefix: com.shimondeitel.cgamelog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Cardgamelog:
    type: application
    platform: iOS
    sources:
      - path: Cardgamelog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.cgamelog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Cardgamelog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  CardgamelogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CardgamelogTests
      - path: Cardgamelog.storekit
    dependencies:
      - target: Cardgamelog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.cgamelog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  CardgamelogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: CardgamelogUITests
    dependencies:
      - target: Cardgamelog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.cgamelog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Cardgamelog:
    build:
      targets:
        Cardgamelog: all
        CardgamelogTests: [test]
        CardgamelogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Cardgamelog.storekit
    test:
      config: Debug
      storeKitConfiguration: Cardgamelog.storekit
      targets:
        - CardgamelogTests
        - CardgamelogUITests
    archive:
      config: Release
